### ISSUE TITLE
Bump wagtail-localize requirements

### ISSUE THREAD

**Issue by TheoChevalier** [wagtail/wagtail-localize-pontoon#25]
Hi,

It looks like the latest wagtail-localize-git release (0.12) is preventing the upgrade to the latest release of wagtail-localize (1.1.1), would it be possible to bump the requirements?

<img width="753" alt="Capture d’écran 2022-03-25 à 14 07 27" src="https://user-images.githubusercontent.com/1294206/160126668-fdf524a7-311c-4e7b-92ca-09c43cecb11b.png">

**Comment by zerolab** [comment]
https://github.com/wagtail/wagtail-localize-git/releases/tag/v.0.13.0 takes care of this and more
